repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: pretty-format-json
        exclude: Pipfile.lock
        args: ["--autofix"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.18.1"
    hooks:
      - id: mypy
        additional_dependencies:
          - types-toml
        exclude: tests
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.0
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
