# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  install-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python
      - name: Lint
        run: |
          pip install pipenv
          pipenv install --dev
          python -m pre-commit run --all-files

      - name: Test
        run: |
          python -m pytest --cov
